---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  namespace: monitoring
  labels:
    type: nfs
    app: prometheus-deployment
spec:
  storageClassName: standard
  hostPath:
    path: /opt/sr/data
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
