apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-grafana
  namespace: monitoring
  labels:
    type: nfs
spec:
  storageClassName: standard
  hostPath:
    path: /opt/sr/data
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
