kind: PersistentVolume 
apiVersion: v1 
metadata: 
  name: postgres-pv-volume
  namespace: monitoring
  labels: 
    type: local 
    app: postgres 
spec: 
  storageClassName: standard
  capacity: 
    storage: 5Gi 
  accessModes: 
    - ReadWriteMany 
  hostPath: 
    path: "/opt/data" 
