apiVersion: v1
kind: Secret
metadata:
  name: my-postgres-secret
  namespace: monitoring
type: Opaque
data:
  POSTGRES_HOST: MTI3LjAuMC4x
  POSTGRES_PORT: NTQzMg==
  POSTGRES_DB: cG9zdGdyZXNkYg==
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: dGVzdDEyMw==
